name: Scheduled Workflow

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  my-scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a script
        run: echo "This job runs on a schedule!"
